site_name: LoggingUtil Documentation
site_description: A powerful Python logging utility that surpasses the standard library
repo_url: https://github.com/mochathehuman/loggingutil
repo_name: mochathehuman/loggingutil

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Quick Start: guide/quickstart.md
    - Configuration: guide/configuration.md
    - Handlers: guide/handlers.md
    - Filters: guide/filters.md
    - Cloud Integration: guide/cloud.md
  - API Reference:
    - LogFile: api/logfile.md
    - Handlers: api/handlers.md
    - Filters: api/filters.md
    - Configuration: api/config.md
    - CLI: api/cli.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 