site_name: LoggingUtil
site_description: A powerful Python logging utility that surpasses the standard library logging module
repo_url: https://github.com/mochathehuman/loggingutil
repo_name: mochathehuman/loggingutil

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [loggingutil]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 3
  - autorefs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - API Reference:
    - LogFile: api/logfile.md
    - Handlers: api/handlers.md
  - Guides:
    - Cloud Integration: guide/cloud.md
  - Changelog: changelog.md 